version: '3.8'

services:
  backend:
    build: .
    container_name: song-library-backend
    ports:
      - '3000:3000'
    depends_on:
      - postgresDB
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresDB:5432/${POSTGRES_DB}
  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=songsdb

volumes:
  postgres_data:
