version: '3.8'

services:
  backend:
    build: .
    container_name: song-library-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongoDB
    environment:
      - MONGO_URL=mongodb://mongoDB:27017/songsdb
  
  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongoDB_data:/data/db


volumes:
    mongoDB_data:

